skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
private_transfers = "DQaB98bRsVCThsUqbRDH7CJYBCD2WeMHQbhHfWKKFCwU"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]


[test]
startup_wait = 5000

[[test.genesis]]
address = "27pnB3zKnQ7uC2saTV6jMzumNf8WYra6AxJjbLN5JftE" 
program = "circuits/withdrawal/target/withdrawal.so"